var brand_MainBrandPick;
brand_MainBrandPick = "";
brand_MainBrandPick+="<section class='brandStreetV15a'>"
brand_MainBrandPick+="<div class='swiper-container swiper1'>"
brand_MainBrandPick+="<div class='swiper-wrapper'>"
brand_MainBrandPick+="<div class='swiper-slide'>"
brand_MainBrandPick+="	<a href=javascript:fnAPPpopupBrand('manet01');><div class='brandInfoV15a'>"
brand_MainBrandPick+="		<strong>MANET</strong>"
brand_MainBrandPick+="		<p>디자인은, 좋아하는것을 함께 나누고 싶은 마음</p>"
brand_MainBrandPick+="	</div>"
brand_MainBrandPick+="	<img src='http://imgstatic.10x10.co.kr/brandstreet/main/brandpick/2411_mainBrandPick.jpg' alt='브랜드Pick1' /></a>"
brand_MainBrandPick+="</div>"
brand_MainBrandPick+="<div class='swiper-slide'>"
brand_MainBrandPick+="	<a href=javascript:fnAPPpopupBrand('arenazz');><div class='brandInfoV15a'>"
brand_MainBrandPick+="		<strong>Blooming&me</strong>"
brand_MainBrandPick+="		<p>디자인은, 작지만 따뜻한 아름다움을 전할 수 있는 것</p>"
brand_MainBrandPick+="	</div>"
brand_MainBrandPick+="	<img src='http://imgstatic.10x10.co.kr/brandstreet/main/brandpick/2412_mainBrandPick.jpg' alt='브랜드Pick2' /></a>"
brand_MainBrandPick+="</div>"
brand_MainBrandPick+="<div class='swiper-slide'>"
brand_MainBrandPick+="	<a href=javascript:fnAPPpopupBrand('LIVEWORK');><div class='brandInfoV15a'>"
brand_MainBrandPick+="		<strong>LIVEWORK</strong>"
brand_MainBrandPick+="		<p>디자인은, 일상 속의 작은 감성</p>"
brand_MainBrandPick+="	</div>"
brand_MainBrandPick+="	<img src='http://imgstatic.10x10.co.kr/brandstreet/main/brandpick/2413_mainBrandPick.jpg' alt='브랜드Pick3' /></a>"
brand_MainBrandPick+="</div>"
brand_MainBrandPick+="<div class='swiper-slide'>"
brand_MainBrandPick+="	<a href=javascript:fnAPPpopupBrand('disney10x10');><div class='brandInfoV15a'>"
brand_MainBrandPick+="		<strong>Disney Edition</strong>"
brand_MainBrandPick+="		<p>디자인은, 디즈니의 빈티지 감성을 통해 추억과 향수를 불러일으키는 것</p>"
brand_MainBrandPick+="	</div>"
brand_MainBrandPick+="	<img src='http://imgstatic.10x10.co.kr/brandstreet/main/brandpick/2414_mainBrandPick.jpg' alt='브랜드Pick4' /></a>"
brand_MainBrandPick+="</div>"
brand_MainBrandPick+="</div>"
brand_MainBrandPick+="</div>"
brand_MainBrandPick+="<div class='bnrPagingV15a'></div>"
brand_MainBrandPick+="</section>"
document.write(brand_MainBrandPick);
